version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: postgresql:8.0.27
    restart: always
    environment:
      - POSTGRES_ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_DATABASE=warehouseData
    ports:
      - "5432:5432"
    command: postgresql --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
  app-server:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/dataWH
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    expose:
      - "8099"
    command: mvn clean spring-boot:run
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    volumes:
      - ~/.m2:/root/.m2
      - .:/app

